### ISSUE TITLE
[Feature request] Title should take presedence over content

### ISSUE THREAD

**Issue by aamirazad** [scambier/obsidian-omnisearch#403] opened 2024-09-27 21:50 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try to search for a file by typing it's **exact** filename the search is like, nah, your thinking of something else and ranks it like 7th result. Giving me windows search vibes. As you can see in the video below, I think the cause of this is the number two having many hits on another article, but I do not really care, its not what I want. 

**Describe the solution you'd like**
I think in the case that the title of the note is almost or exactly matching the query, it should be the first result.

**Describe alternatives you've considered**
There are some search patters that work and some that do not work. Its just trial and error. 

**Additional context**
Please watch this video to understand what I'm talking about. Thanks!

https://github.com/user-attachments/assets/e84a10aa-b04f-4c7f-8251-d2bb7eab5c7e

**Comment by scambier** [comment] 2024-09-28 07:41
Duplicate of #289

In the meantime, boosting the weighting of titles could help
![image](https://github.com/user-attachments/assets/e3ca5191-f20f-438b-aeb7-112ffe112fcb)

**Closed by scambier** 2024-09-28 07:41 UTC
