### ISSUE TITLE
[BUG] Highlighted results remove surrounding spaces

### ISSUE THREAD

**Issue by kjy5** [scambier/obsidian-omnisearch#244] opened 2023-05-21 21:37 UTC
**Problem description:**

- When results highlight the search term, the surrounding spaces disappear
<img width="611" alt="Screenshot 2023-05-21 at 2 32 30 PM" src="https://github.com/scambier/obsidian-omnisearch/assets/82800265/8830aa8c-db26-4e7d-abb5-bb3f536ee409">

**Your environment:**

- Omnisearch version: 1.14.0 (latest as of writing this)
- Obsidian version: 1.2.8 (latest as of writing this)
- Operating system: macOS Ventura 13.4
- No theme used (default Obsidian theme)
- Interface font: Inter

**Things to try:**

- Does the problem occur when Omnisearch is the only active community plugin: 👍
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files: 👍
- Does the problem occur after a cache reset: 👍
- Does the problem occur with the default themes and fonts: 👍

**Comment by scambier** [comment] 2023-05-22 04:44
Dupe of #236 & fixed by #239 in beta. I'll probably publish it in stable at the end of this week.

**Closed by scambier** 2023-05-22 04:44 UTC
