### ISSUE TITLE
[Feature request] Locate Index/Cache on Mobile

### ISSUE THREAD

**Issue by zanodor** [scambier/obsidian-omnisearch#143] opened 2022-12-03 11:54 UTC
**Is your feature request related to a problem? Please describe.**
I have a pretty big vault. During building index, app exits persistently. 

I'd say the most important thing when you have a large repository of information is the ability to search. As I mainly use a handheld device, I'd love to have this indispensable feature on it.  

**Describe the solution you'd like**
I'd like the ability to use index/cache built on PC to be used on mobile.  

**Question**
What does the Clear Cache Data option in Settings mean? Will the app not try to reindex on mobile/PC unless you purge?  
I'd love an option on mobile that keeps my index untouched unless I want it to be updated.

Thanks, 

Best regards,
Z.

**Comment by scambier** [comment] 2022-12-03 13:18
I'm interested to know if [the current beta ](https://github.com/scambier/obsidian-omnisearch/releases/tag/1.9.0-beta.6) causes the same problems for you. It should consume less memory, that could solve the crashes. If that fails, I will implement a basic export/import feature for the cache.

> What does the Clear Cache Data option in Settings mean? Will the app not try to reindex on mobile/PC unless you purge?
I'd love an option on mobile that keeps my index untouched unless I want it to be updated.

The "cache" here is the serialized search index. It is used to avoid a full reindex each time you restart Obsidian. [Related discussion](https://github.com/scambier/obsidian-omnisearch/discussions/140).

**Comment by scambier** [comment] 2022-12-03 18:25
Ok I initially thought that you were using an Android, but the problem with iOS is already known: see #120 

> 14500 notes

In that extreme case, that's just too many notes and not enough memory :/ Actually, the cache is disabled on iOS devices because loading it causes a spike in memory use, which triggers a force-close from iOS. Even worse, since the cache is loaded at startup, Obsidian crashes immediately without letting you the time to disable Omnisearch.

I can't think of a solution that doesn't involve creating an omnisearch online api, sorry 😅

> If I can have IndexDB compiled on the PC, where is it stored and can I copy that file to the Pad?

IndexedDB is an in-browser database, and there's not built-in way to export/import the data from/to another device. There are some packages to help with the task, but it still needs to be built within Omnisearch. But like I said, it wouldn't solve the crashes.

I'm closing this issue as it is a duplicate of #120, but you're welcome to continue the discussion over there.

**Closed** 2022-12-04 21:28 UTC
