### ISSUE TITLE
[Feature request] Add partial match for file names

### ISSUE THREAD

**Issue by charleshan** [scambier/obsidian-omnisearch#194] opened 2023-02-11 21:13 UTC
**How to reproduce the problem:**
1. Assume that this project was called ObsidianOmnisearch.
2. Create a file named `ObsidianOmnisearch`.
3. Search for `Omnisearch`.
4. I expect `ObsidianOmnisearch` file to show up but it doesn't.

**Describe the solution you'd like**
Add partial match for file names.

I see that you said, "The underlying algorithm does not support partial matches, except for the prefixes and fuzzy matches. That's a necessary tradeoff for the search speed and weighted results on larger vaults" (https://github.com/scambier/obsidian-omnisearch/issues/35). I'm not expecting partial match for everything— just the file names. Searching for `Omnisearch` works for the default QuickSwitcher and AnotherQuickSwitcher so I think it's important to support this for people to use this plugin as the default way to open files.

**Comment by scambier** [comment] 2023-02-12 08:17
Would the solution proposed in #176 be acceptable? It seems it fits your use case

**Comment by charleshan** [comment] 2023-02-12 22:40
I believe you're referring to "CamelCaseWord" as "Camel"+"Case"+"Words"?

That would solve this particular use case but I have more use cases. Some asian languages (Korean, Chinese, etc) connect last name and first name into one word. Omnisearch does not let me look up anyone with their first name. I'll try adding a space in between the words to solve this issue but, as I said before, I think it's important to get feature parity to let people choose Omnisearch over QuickSwitcher without a second thought.

**Comment by charleshan** [comment] 2023-02-19 19:27
Another annoyance that I just came across: Searching for "GPT" but the search doesn't include "ChatGPT"

**Comment by AnweshGangula** [comment] 2023-06-19 15:29
It would be very useful to extend this functionality even with file content searches, not just file name.
If it does have any performance impacts, adding a toggle _(with warning)_ to enable/disable it would be better.

**Comment by scambier** [comment] 2023-06-19 15:46
@charleshan 
>  Some asian languages (Korean, Chinese, etc) connect last name and first name into one word. Omnisearch does not let me look up anyone with their first name. (...)  let people choose Omnisearch over QuickSwitcher

Is this something that QuickSwitcher does (splitting names in CJK languages)? Omnisearch 100% relies on https://github.com/aidenlx/cm-chs-patch to split words in CJK, I have no idea how that works with firstnames/lastnames.

> Searching for "GPT" but the search doesn't include "ChatGPT"

This should be fixed with #176

**Comment by charleshan** [comment] 2023-06-21 06:02
@scambier 

I just checked that QuickSwitcher matches partial letters (also can be considered words) for CJK languages.
e.g. With a file named 가나다, I can search 나다 or even 다 to match the file.

Also, QuickSwitcher also matches "ChatGPT" when I search "GPT"

**Comment by scambier** [comment] 2024-02-23 15:57
Closing this: for latin languages the issue is already solved with #176. For CJK, Omnisearch depends on the tokenization by cm-chs-patch.

**Closed by scambier** 2024-02-23 15:57 UTC
Labels: enhancement
