### ISSUE TITLE
[BUG]  inject results in Google has minor (CSS?) layout issues

### ISSUE THREAD

**Issue by mgiugliano** [scambier/obsidian-omnisearch#347] opened 2024-03-06 13:53 UTC
**Problem description:**

Filenames and note title graphically overlap (due to misalignment?), as the search results are "injected" and displayed in a Google search. This makes it a bit difficult to read it.

<img width="1583" alt="Screenshot 2024-03-06 at 14 43 16" src="https://github.com/scambier/obsidian-omnisearch/assets/9309421/0d1d1d9a-8f0d-489e-8843-b385dbe29d24">

**Your environment:**

- Omnisearch v: 1.21.1
- Obsidian v: 1.5.8
- OS v: macOS Sonoma 14.3.1
- N indexed docs: <50

- The problem does occur when Omnisearch is the only active community plugin.
- The problem does occur when I _don't_ index PDFs, images,...
- The problem does occur after a cache reset.

**Comment by scambier** [comment] 2024-03-06 20:39
Duplicate of https://github.com/scambier/userscripts/issues/22, and should be fixed 👍

**Closed by scambier** 2024-03-06 20:39 UTC

**Comment by mgiugliano** [comment] 2024-03-06 21:21
Thanks for your excellent work! I need to study Omnisearch well but I can already tell it is a game changer (as I was thinking of Notational Velocity vim plugin as a note search engine).
