### ISSUE TITLE
[BUG] No PDF results on iOS

### ISSUE THREAD

**Issue by ely-see** [scambier/obsidian-omnisearch#395] opened 2024-09-17 18:29 UTC
**Problem description:**
Hello, 

I try to use Omnisearch on iOS. Unfortunately, the PDF indexing doesn’t show any results. I save the index to the cache and sync it with Obsidian sync. Text Extractor is installed. On Desktop, all works fine.

**Your environment:**

- Omnisearch version: 1.24.0
- Obsidian version: 1.6.7
- Operating system: iOS
- Number of indexed documents in your vault (approx.): 59 

**Things to try:**

- Does the problem occur when Omnisearch is the only active community plugin:  Yes.
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files:  Not tried as I exactly want this. 
- Does the problem occur after a cache reset: Yes

**Comment by Prateek-coder19** [comment] 2024-10-24 19:10
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by scambier** [comment] 2024-11-25 08:35
Duplicate of https://github.com/scambier/obsidian-text-extractor/issues/64

**Closed by scambier** 2024-11-25 08:35 UTC
