### ISSUE TITLE
[Feature request] Option to open in a new tab

### ISSUE THREAD

**Issue by ethanmiller1** [scambier/obsidian-omnisearch#213] opened 2023-03-18 16:12 UTC
[Quick Switcher++](https://github.com/darlal/obsidian-switcher-plus) has a feature to open a new editor tab by default when navigating to un-opened files. Can we get this option in obsidian-omnisearch?

![New Tab with Quick Switcher++](https://user-images.githubusercontent.com/40644725/226118490-d901ec47-f678-42c1-97ed-228b931517cc.gif)

**Comment by scambier** [comment] 2023-03-18 17:07
Duplicate of #175?

You can also ctrl+enter or middle-click on a result to open it in a new tab.

**Closed** 2023-03-20 07:52 UTC
