### ISSUE TITLE
[Feature request] Render Markdown in Search Results

### ISSUE THREAD

**Issue by zcysxy** [scambier/obsidian-omnisearch#197] opened 2023-02-18 19:16 UTC
**Is your feature request related to a problem? Please describe.**
Currently, the search results provide a preview of the source code. It would provide clearer information if it can render it as Markdown. This FR is related to #36.

**Describe the solution you'd like**
Use Obisidian API `MarkdownRenderer` to render the results. For example, see <https://github.com/debanjum/khoj/blob/3ae603bd93a56fe61a83c72f296eb9319c4bbc8e/src/interface/obsidian/src/modal.ts#L92-L99> and this patch <https://github.com/debanjum/khoj/pull/135>. And I noticed no performance delay.

**Comment by scambier** [comment] 2024-11-25 12:18
Duplicate of #36

**Closed by scambier** 2024-11-25 12:18 UTC
