### ISSUE TITLE
[BUG] When indexing obsidian hangs and the whole interface is replaced by a white screen. 

### ISSUE THREAD

**Issue by smirnovmaksim91** [scambier/obsidian-omnisearch#182] opened 2023-01-18 18:32 UTC
When I install or reinstall omnisearch on my MacBook, obsidian hangs and the entire application window goes completely white. If I leave it in this state, nothing changes. If I do a restart that after a while the situation repeats. If you have time to turn off omnisearch when you turn it on again, it works fine. 
On the iPad everything works and there are no glitches.

**Comment by scambier** [comment] 2023-01-18 18:41
Could you please answer the questions asked in the template please? https://github.com/scambier/obsidian-omnisearch/issues/new?assignees=&labels=&template=bug_report.md&title=%5BBUG%5D+

**Comment by smirnovmaksim91** [comment] 2023-01-18 19:05
**Problem description:**
When I install or reinstall omnisearch on my MacBook, obsidian hangs and the entire application window goes completely white. If I leave it in this state, nothing changes. If I do a restart that after a while the situation repeats. If you have time to turn off omnisearch when you turn it on again, it works fine.
On the iPad everything works and there are no glitches.

loaded icon pack font-awesome-brands (459)
iconPackManager.ts:283 loaded icon pack font-awesome-regular (161)
iconPackManager.ts:283 loaded icon pack font-awesome-solid (1128)
iconPackManager.ts:283 loaded icon pack icon-brew (284)
iconPackManager.ts:283 loaded icon pack remix-icons (2271)
iconPackManager.ts:283 loaded icon pack simple-icons (2413)
index.ts:162 Dataview: Dropped cache entries for 1 deleted files.
plugin:obsidian42-brat:18 BRAT: Checking for plugin updates STARTED
plugin:obsidian42-brat:18 BRAT: Checking for plugin updates COMPLETED
DevTools failed to load source map: Could not load content for app://obsidian.md/S%20-%20Checkboxes.css.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for app://obsidian.md/theme.css.map: System error: net::ERR_FILE_NOT_FOUND
plugin:omnisearch:39 Text Extract - Number of available workers: 5
plugin:omnisearch:47 Omnisearch - 2218 files total
plugin:omnisearch:47 Omnisearch - Loading index from cache: 113.72900390625 ms
plugin:omnisearch:47 Omnisearch - Total number of files to add/update: 2218
![Screenshot 2023-01-18 at 22 03 16](https://user-images.githubusercontent.com/70570280/213271459-b2e62403-4953-48bf-acce-a670abd06fb9.png)

**Your environment:**


- Omnisearch version: 
- Obsidian version: 1.1.9
- Operating system: MacOS 13.1
- Number of indexed documents in your vault (approx.): 2300

**Things to try:**
- Does the problem occur when Omnisearch is the only active community plugin: Yes
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files:  Yes
- Does the problem occur after a cache reset: Yes

**Comment by scambier** [comment] 2023-01-18 19:57
This could be a duplicate of #159. What's interesting is that it _does not_ freeze on iPad, which has cache disabled.

Could you try this build and report back please? [omnisearch 182 fix 1.zip](https://github.com/scambier/obsidian-omnisearch/files/10450238/omnisearch.182.fix.1.zip)

**Comment by smirnovmaksim91** [comment] 2023-01-18 20:09
This build works (image and pdf search disabled). Thank you very much!

**Closed** 2023-01-18 20:14 UTC
Labels: bug
