### ISSUE TITLE
[BUG] Failed to load plugin omnisearch

### ISSUE THREAD

**Issue by Bakr-Ali** [scambier/obsidian-omnisearch#137] opened 2022-11-28 17:33 UTC
**Problem description:**

after installing the plugin on iPadOS, I get the error "Failed to load plugin omnisearch" when trying to enable it. I’ve created a new empty vault and tried installing the plugin there but I still get the same error.

**Your environment:**

- Omnisearch version: 1.8.1
- Obsidian version: 1.4.1
- Operating system: iPadOS 14.4
- Number of notes in your vault (approx.): 0
- Other plugins that may be related to the issue: None

**Comment by scambier** [comment] 2022-12-09 10:30
@Bakr-Ali I've published a new version yesterday (1.9.0), does it still crash for you?

**Comment by Bakr-Ali** [comment] 2022-12-09 18:01
@scambier Yes, it still crashes.

**Comment by scambier** [comment] 2022-12-11 20:17
I'll have to get the logs to know what's going on. The easiest way (I think) is the following:

1) Install the community plugin "Obsidian 42 - BRAT"
2) Use the command "BRAT: Plugins: add a beta plugin for testing"
3) Install the dev tools from this url:  `https://github.com/KjellConnelly/obsidian-dev-tools`, and activate it
4) Use the command "Obsidian Dev Tools Plugin: Toggle Console"
5) Restart Obsidian and collect the logs

**Comment by Bakr-Ali** [comment] 2022-12-11 22:46
Here is the error I get:

![7324774D-614C-4C76-B904-DAB870CBC9BB](https://user-images.githubusercontent.com/49000030/206933311-3c8d8d0c-4c3b-4ef9-9f6c-d36a243147d8.jpeg)

**Comment by scambier** [comment] 2022-12-12 21:00
It seems to be the same issue as https://github.com/AlexW00/obsidian-note-linker/issues/5, which references https://github.com/ionic-team/capacitor/pull/5585. Omnisearch also uses wasm, but I'm puzzled since you're - so far - the only iOS user affected. That doesn't really make sense, unless all iOS users are too polite to report the bug 🤷‍♂️

Anyway, here are 2 test builds.
- [omnisearch 137 dynamic.zip](https://github.com/scambier/obsidian-omnisearch/files/10211979/omnisearch.137.dynamic.zip) dynamically loads the wasm dependency on non-mobile devices only
- [omnisearch 137 no wasm.zip](https://github.com/scambier/obsidian-omnisearch/files/10211970/omnisearch.137.no.wasm.zip) entirely removes the dependency

If you could try both and report the results, I'd appreciate it a lot!

**Comment by Bakr-Ali** [comment] 2022-12-13 00:35
The dynamic build gave me the same error, while the no wasm build worked!

> you're - so far - the only iOS user affected.
Maybe most users don’t update their plugins after initial installation?

It took me a while (and some Googling) to copy the files to the correct directories since the `.obsidian` folder is hidden in iOS and I needed to use some Linux commands that I’m not familiar with. I’ll document how I did it here for future reference if you don’t mind:
Using the FOSS app a-shell mini:
- `pickFolder` and select the test obsidian vault folder (On my iPad > Obsidian > Test-omni).
- Move and extract the zip files to the same directory.
- `cp -R omnisearch.137.dynamic .obsidian/plugins/ `.
- `rm -r .obsidian/plugins/ omnisearch.137.dynamic`.

Thanks for the free plugin and support!

**Comment by scambier** [comment] 2022-12-13 19:36
> Maybe most users don’t update their plugins after initial installation?

😄 I think most do. And I had a few iOS beta testers when I was implementing PDF indexing (which uses wasm & workers). Is your iOS device different in any way?

I'd like to identify the root issue, or at least not have to make different builds for different devices.

**Comment by Bakr-Ali** [comment] 2022-12-15 10:36
> Is your iOS device different in any way?

No, it is a regular old iPad Pro 9.7" that have never been modified or jailbroken.

Is there no other way of debugging that I can help with?

**Comment by scambier** [comment] 2022-12-21 20:21
Well, since it looks like you're the only person affected, I don't quite know what to do in the short term (besides making you custom builds). Do you have access to another iOS device to reproduce this issue?

In the longer term, I'll get rid of the wasm stuff in Omnisearch so this issue will eventually solve itself

**Comment by Bakr-Ali** [comment] 2022-12-24 11:32
> Do you have access to another iOS device to reproduce this issue?

No, I don’t.

**Comment by scambier** [comment] 2023-01-21 07:46
The last update removed wasm, your issue should be fixed :)

**Closed by scambier** 2023-01-21 07:46 UTC
Labels: bug, help wanted
