### ISSUE TITLE
[BUG] Search results are wrong

### ISSUE THREAD

**Issue by Nelvin** [scambier/obsidian-omnisearch#261] opened 2023-07-25 08:29 UTC
**Problem description:**

Wrong search results

**Your environment:**

- Omnisearch version: 1.15.0
- Obsidian version: 1.3.5
- Operating system: Windows 10
- Number of indexed documents in your vault (approx.): 1

**Things to try:**

- Does the problem occur when Omnisearch is the only active community plugin:  yes
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files:  yes
- Does the problem occur after a cache reset: yes

I tried to use Omnisearch in my vault but the results didn't match what I expected so I did some test with a new and empty vault with a tiny single note.

I used an out of the box new vault with just Omnisearch installed and a hotkey configured.
[test.md](https://github.com/scambier/obsidian-omnisearch/files/12158839/test.md)
[dummy_vault.zip](https://github.com/scambier/obsidian-omnisearch/files/12158822/dummy_vault.zip)

Here are some screenshots of different searches and basically none with the results I expected.

Vault search for content - 5 matches but the note only includes the word 4 times
![Clipboard Image](https://github.com/scambier/obsidian-omnisearch/assets/3474781/7b45fc12-0f2e-4029-a8da-8d87285f2fe2)

In file search for content - only one match
![infile_content](https://github.com/scambier/obsidian-omnisearch/assets/3474781/ed4b2232-a560-4b6a-95ae-490165818378)

Vault search for depends - 2 matches but the note includes the word only once
![vault_depends](https://github.com/scambier/obsidian-omnisearch/assets/3474781/ffab8d1c-169b-473f-a1a5-bec684bb9066)

In file search for depends - 2 matches/previews shown, the number actually as expected given the vault search but again wrong as it shows the same result twice
![infile_depends](https://github.com/scambier/obsidian-omnisearch/assets/3474781/650cce33-80be-43fc-ab7e-a46c3a9ec282)

What I expected for the vault search is, that the number of matches equals the number of occurrences of the words I searched for and the in file search to give me the same number of previews so I can jump to the result within a note or at least to the section/paragraph.

**Comment by scambier** [comment] 2023-07-26 04:50
There was indeed a bug with the matches counter, that should be fixed with the latest update.

Regarding the In-File results, I can say "it's not a bug, it's a feature" :) Results are grouped together when they're close enough, to avoid e.g having 3 results that point to 2 consecutive lines. The number of matches is unrelated to the number of In-File results.

**Closed** 2023-07-27 12:14 UTC

**Comment by Nelvin** [comment] 2023-07-29 17:14
Thanks for the fast fix - was the fix a comsmetic one only, i.e. just changed the number? I also had situations where I ended in a wrong place within a file with multiple search results and, so far, I haven't had this anymore (might just be a coincidence though).

Anyway, thanks a lot for the quick fix. I do have an opinion about combined search result but knowing it's intended I'll think about it and may write a enhancement suggestion for it.

**Comment by scambier** [comment] 2023-07-30 17:56
> was the fix a comsmetic one only, i.e. just changed the number? 

If your query can be found literally in a resulting note (when you're searching for multiple words), I put this "perfect match" at the top. I just forgot to remove it before moving it to the top, so there was one too many matches https://github.com/scambier/obsidian-omnisearch/commit/3f5269e4984e2151dfe4fc98d75bde01ab49295e#diff-56dcf56cea23f2bf032ae9377e57215ed609b59e637cad9f56c94748593944f1R361
