### ISSUE TITLE
[BUG] Umlauts are not displayed in search

### ISSUE THREAD

**Issue by antoKeinanen** [scambier/obsidian-omnisearch#258] opened 2023-07-10 14:26 UTC
**Problem description:**
Umlauts are the tiny dots above Ää Öö and for some reason, they are not displayed in the search results as seen in the screenshot. (the result should be Lämpö as searched)

![image](https://github.com/scambier/obsidian-omnisearch/assets/62938747/54474764-974e-454d-81a6-4b192111beb2)

**Your environment:**

- Omnisearch version: 1.14.2
- Obsidian version: 1.3.5
- Operating system: Windows and Linux
- Number of indexed documents in your vault (approx.): 200

**Things to try:**

- Does the problem occur when Omnisearch is the only active community plugin:  yes
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files:  yes
- Does the problem occur after a cache reset: yes

**Comment by scambier** [comment] 2023-07-10 15:49
Duplicate of #190

**Closed by scambier** 2023-07-10 15:49 UTC
