### ISSUE TITLE
[Feature request] JetBrains Global search preview like

### ISSUE THREAD

**Issue by ctwhome** [scambier/obsidian-omnisearch#315] opened 2023-11-12 13:47 UTC
In Webstorm and other JetBrains IDEs, there is the most useful thing I have ever used and that is the preview search floating. It allows me to navigate between the results without changing the context. It is supper useful, not destructive and it allows you to quickly find and modify things on the fly without losing focus on what you are doing. 

https://github.com/scambier/obsidian-omnisearch/assets/4195550/6b87ce3f-f14a-460b-a02b-66a6d2f9c4d7

![image](https://github.com/scambier/obsidian-omnisearch/assets/4195550/f48309bd-15db-466e-9dd1-f57a9a31e58b)

**Comment by scambier** [comment] 2023-11-24 10:42
I'll close this as a duplicate of #36. Reopen if it's not :)

**Closed by scambier** 2023-11-24 10:42 UTC
