### ISSUE TITLE
[Feature request] Jump to exact location within note for matched string

### ISSUE THREAD

**Issue by ammarhusain** [scambier/obsidian-omnisearch#301] opened 2023-10-06 21:00 UTC
**Is your feature request related to a problem? Please describe.**
When I search my vault for a particular string and open the note containing it - Omnisearch always just opens and brings me to the top of the note rather than its exact location in the note file. I have certain notes that are fairly long. This gets cumbersome since I then need to do an in-note search for the exact string again to get to the exact location. This makes a simple one step search into an unnecessary two step process.

**Describe the solution you'd like**
Should jump to the exact location within the note for where the matched string is.

**Describe alternatives you've considered**
Using the default Obsidian search - but its not that great.

**Additional context**
https://www.reddit.com/r/ObsidianMD/comments/151qcsq/omnisearch_help/

**Comment by scambier** [comment] 2023-10-07 07:52
That's a bug, duplicate of #298

Can you reproduce it reliably, or does it only happen with certain documents?

**Comment by ammarhusain** [comment] 2023-10-07 15:19
It seems to happen with quite a few documents so yes I can reproduce it reliably. May be it is struggling with long notes.

**Closed** 2023-11-01 10:00 UTC
