### ISSUE TITLE
[Feature request] Ability to use some kind of custom field in results weighing

### ISSUE THREAD

**Issue by daamiian** [scambier/obsidian-omnisearch#251] opened 2023-06-20 10:26 UTC
**Is your feature request related to a problem? Please describe.**
I use a version of this line in pretty much every single note:
`**Search Terms:** fndpm glossary, foundpm term, fndpm gloss, fndpm terms`
this one is for a note titled: `Foundations of Project Management Glossary of Terms`.

The idea is to give me a lot of flexibility when fuzzy searching. 

The problem is omnisearch doesn't care about it at all. Quick switcher picks up on these words if I search them, but omnisearch surprisingly pulls zero results from "fndpm gloss" which is directly mentioned in the note letter for letter. I suspect this has to do with the results weighing.

**Describe the solution you'd like**

I think if there were more flexibility in results weighing, like certain yaml properties (I could easily make the search terms a yaml property), this issue would be resolved for me. 

**Describe alternatives you've considered**

**Additional context**
I am still concerned that the "fndpm gloss" body text displayed no results at all, despite there being a note in my vault with that exact letter combination. Maybe this is a bug.

**Comment by scambier** [comment] 2023-06-20 10:31
> omnisearch surprisingly pulls zero results from "fndpm gloss"

That's definitely not normal, and it works on my test vault. Does this note appears in results when you search some other words?

For your request, I guess this is a dupe of #151. I'll eventually work on it 👍

**Comment by daamiian** [comment] 2023-06-20 10:32
Wow that was quick! I just went to reproduce and of course AFTER I post it's working fine. Sorry for the mislead.

The feature would still be nice to add a yaml property to results weighing though.

**Closed** 2023-06-20 10:33 UTC
