### ISSUE TITLE
[BUG] Omnisearch only Indexes the First Time after Install, Never Again

### ISSUE THREAD

**Issue by LloydThinks** [scambier/obsidian-omnisearch#170] opened 2023-01-10 10:33 UTC
**Problem description:**

I have found that every time I use the Omnisearch search, I see `⏳ Work in progress: Indexing files...` message. Opening the console, I see the following:

```log
loading markdown-table-editor plugin
plugin:hotkeysplus-obsidian:43 Loading Hotkeys++ plugin
plugin:omnisearch:43 Text Extract - Number of available workers: 5
plugin:omnisearch:50 Omnisearch - 689 files total
plugin:omnisearch:50 Omnisearch - Loading index from cache: 1786.44189453125 ms
plugin:omnisearch:50 Omnisearch - Total number of files to add/update: 1
plugin:omnisearch:50 Omnisearch - Total number of files to remove: 1
```

It appears that OmniSearch is aware of what it needs to re-index, but then nothing happens. Clearing the cache, and starting Obsidian again, produces the same message.

If I uninstall OmniSearch, and re-install it, I get the same behaviour, but now there are many more PDFs to index:

```log
loading markdown-table-editor plugin
plugin:hotkeysplus-obsidian:43 Loading Hotkeys++ plugin
plugin:omnisearch:43 Text Extract - Number of available workers: 5
plugin:omnisearch:50 Omnisearch - 689 files total
plugin:omnisearch:50 Omnisearch - Loading index from cache: 233.615966796875 ms
plugin:omnisearch:50 Omnisearch - Total number of files to add/update: 507
```

The only way I have been able to force OmniSearch to index new PDFs is to delete the following two databases in the Developer Console:
- obsidian-text-extract/cache/...
- omnisearch/cache/...

**Your environment:**

- Omnisearch version: 1.9.1
- Obsidian version: 1.1.9
- Operating system: macOS Ventura 13.0
- Number of notes in your vault (approx.): 134 MD files, 481 PDFs in a Resources folder. Omnisearch says it has `689 files total` before indexing.
- Other plugins that may be related to the issue: Full plugin list: Advanced Tables, Footnote Shortcut, Hotkeys++, Linter, and Omnisearch

Thank you,
Lloyd

**Comment by scambier** [comment] 2023-01-10 19:13
> It appears that OmniSearch is aware of what it needs to re-index, but then nothing happens

There seems to be a file that makes Omnisearch freeze without triggering an error. It hangs and does not correctly terminate the indexing process.

A few additional questions:
- Does the problem appear when PDFs and images are _not_ indexed?
- Do you have anything in the "Additional files to index" field?

-> The total files count is `.md` files + images (if enabled) + PDFs (if enabled) + "additional files" (if any)

**Comment by LloydThinks** [comment] 2023-01-17 10:34
Alright I did some testing and found some things out.

> Does the problem appear when PDFs and images are not indexed?

No. The indexing process completes.

> Do you have anything in the "Additional files to index" field?

No. Field is blank.

**Comment by scambier** [comment] 2023-01-17 19:08
So the problem is likely "caused" by a PDF. Could install and activate [Text Extractor](https://github.com/scambier/obsidian-text-extractor)? Omnisearch will use it instead of its built-in extractor, and it should be more resilient to avoid deadlocks.

**Comment by LloydThinks** [comment] 2023-01-18 14:33
I have installed Text Extractor and deleted the databases again. Initial extraction and re-indexing appears to be working. I'll keep an eye on it. Not sure if you want to close this issue now, or wait for more testing. I'm fine with either.

Thank you for your help!

**Comment by scambier** [comment] 2023-01-18 15:57
Let's close it for now.

**Closed by scambier** 2023-01-18 15:57 UTC
Labels: bug, waiting for feedback
