### ISSUE TITLE
[Feature Request] Highlight Searched Text in File When Clicking/Enter Search Result

### ISSUE THREAD

**Issue by MrIntellectX** [scambier/obsidian-omnisearch#299] opened 2023-10-04 04:45 UTC
Although it's a minor issue, it would be a nice addition if it doesn't require too much effort.

**Is your feature request related to a problem? Please describe.**
Currently, when I search for text in OmniSearch, it highlights the text in the search modal. However, when I click or press Enter on the search result, it doesn't highlight the same text inside the actual file, which can be a bit confusing.

**Describe the solution you'd like**
I'd like the searched text to be highlighted within the actual file when clicking or pressing Enter on a search result, along with placing the cursor at the highlighted text.

**Comment by scambier** [comment] 2023-10-04 04:49
Duplicate of #65 👍

**Closed by scambier** 2023-10-04 04:49 UTC
