### ISSUE TITLE
[BUG] Results appear without diacritics

### ISSUE THREAD

**Issue by ofalvai** [scambier/obsidian-omnisearch#312] opened 2023-11-05 12:55 UTC
**Problem description:**

I have some notes with diacritics either in the title or in the note body. Even though the search itself works correctly and finds the notes containing these special characters, the results are rendered as if the note itself was normalized.

**Your environment:**

- Omnisearch version: 1.18.1
- Obsidian version: 1.4.16
- Operating system: macOS
- Number of indexed documents in your vault (approx.): 

**Things to try:**

- Does the problem occur when Omnisearch is the only active community plugin:  
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files:  
- Does the problem occur after a cache reset:

**Comment by scambier** [comment] 2023-11-05 14:30
Duplicate of #190

**Closed by scambier** 2023-11-05 14:30 UTC
