### ISSUE TITLE
[BUG] Open result in new tab/pane not working on MacOS

### ISSUE THREAD

**Issue by pcuellar** [scambier/obsidian-omnisearch#243] opened 2023-05-19 19:45 UTC
**Problem description:**

When trying to open a note in a search list on a new tab/pane using the CTRL+SHIFT combination, it opens it in the same tab. I tried all possible combinations with SHIFT, CMD and CONTROL to no avail. 

**Your environment:**

- Omnisearch version: 1.14.0
- Obsidian version: v1.3.1
- Operating system: MacOS Ventura 13.4
- Number of indexed documents in your vault (approx.): 500

**Things to try:**

- Does the problem occur when Omnisearch is the only active community plugin:  Yes
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files:  Yes
- Does the problem occur after a cache reset: Yes

**Comment by cesar-programs** [comment] 2023-09-10 10:36
I am also experiencing this bug; CMD+Enter does not open in a new pane. Also on macOS Ventura 13.4

**Comment by scambier** [comment] 2023-09-10 13:55
I don't own a Mac so can't test it.

Those are the related lines:

https://github.com/scambier/obsidian-omnisearch/blob/d651278b43c5df46accb6ffcf7ce981fe86902e6/src/components/modals.ts#L70-L86

According to Obsidian's API, "_Mod = Cmd on MacOS and Ctrl on other OS_"

**Comment by scambier** [comment] 2024-06-27 19:10
Closing this as I can't reproduce. If the problem still exists on the latest versions of Obsidian & Omnisearch, please provide the following information:

- Does it happen when Omnisearch is **the only** community plugin enabled?
- Does it happen with another community plugin that uses the same cmd+enter combination?

Thank you.

**Closed by scambier** 2024-06-27 19:10 UTC
Labels: bug, help wanted

**Comment by igorsolovki** [comment] 2025-10-01 07:25
same on linux as of Oct 1 2025
Linux alpha 6.16.7-200.fc42.x86_64
Obsidian v1.9.12
Omnisearch v1.27.1

**Comment by iolpltuisciaoln** [comment] 2025-10-01 07:26
same on linux as of Oct 1 2025
Linux alpha 6.16.7-200.fc42.x86_64
Obsidian v1.9.12
Omnisearch v1.27.1
