### ISSUE TITLE
[BUG] In-file search hotkey not triggered in Reader mode

### ISSUE THREAD

**Issue by adamhp** [scambier/obsidian-omnisearch#377] opened 2024-05-30 12:26 UTC
**Problem description:**
This may be expected behavior, but...

- In reader mode, using a defined hotkey to perform "In-file search" does not trigger opening of search dialogue
- Switching to edit mode _does_ trigger search

**Your environment:**
- Omnisearch version: `1.23.0`
- Obsidian version: `1.5.12`
- Operating system: `Sonoma 14.5`
- Number of indexed documents in your vault (approx.): <50

**Things to try:**
- Does the problem occur when Omnisearch is the only active community plugin: ✔️
- Does the problem occur when you _don't_ index PDFs, images, or other non-notes files: ✔️
- Does the problem occur after a cache reset: ✔️

**Comment by scambier** [comment] 2024-05-30 12:42
👍 Duplicate of #222

**Closed by scambier** 2024-05-30 12:42 UTC
