### ISSUE TITLE
When using in-search, pressing enter on a match takes me to a (seemingly) random file, but clicking works as expected

### ISSUE THREAD

**Issue by technicalpickles** [scambier/obsidian-omnisearch#19] opened 2022-04-23 13:41 UTC
**Type of issue**

- [x] A bug
- [ ] A performance problem

**Problem description**

I'm trying this out after seeing it on [this reddit thread](https://www.reddit.com/r/ObsidianMD/comments/u2lvho/what_are_some_of_your_current_frustrations_with/) because search has been one of the issues I've had with Obsidian. I setup hot keys to use omnisearch for both in-file and vault searches.

Vault search works well, which is what I really wanted. I tried in-file too, but when I navigate to a search result, and press enter, it takes me to a different file. It seems to something that would match the vault search. If I instead point and click on the search result, it goes to where I'd expect it.

Searching:

![Screen Shot 2022-04-23 at 9 39 45 AM](https://user-images.githubusercontent.com/159/164897523-f17b749c-79cd-4afc-a25b-028b38e5ed94.png)

Result when pressing enter:

![Screen Shot 2022-04-23 at 9 39 59 AM](https://user-images.githubusercontent.com/159/164897733-54fc0334-628b-494a-adb7-46426927e03e.png)

Result when clicking (I highlighted it afterwards for clarity)
![Screen Shot 2022-04-23 at 9 41 14 AM](https://user-images.githubusercontent.com/159/164898921-b0962b33-0368-4103-b6e9-d27275cd2287.png)

**Your environment**

- Operating system: macOS
- Number of notes in your vault (approx.): 2804
- Version of Obsidian: 0.14.2
- Other plugins that may be related to the issue:

**Comment by scambier** [comment] 2022-04-23 14:10
Indeed, it looks like the "press enter" event is triggering the vault search instead of the in-file search, but I cannot reproduce it. 

Would you mind testing this build and see if it works? Just replace the old files in `.obsidian/plugins/scambier.obsidian-omnisearch/`, and restart Obsidian. Thank you!

[omnisearch-test-fix-19.zip](https://github.com/scambier/obsidian-omnisearch/files/8547368/omnisearch-test-fix-19.zip)

**Comment by corinnekaryiu** [comment] 2022-04-24 01:57
The same thing has been happening to me, except it would take me back to my "homepage" (first page in the vault) each time.

The build you posted above seems to fix it! 👍🏻

**Comment by scambier** [comment] 2022-04-26 19:35
This issue should now be fixed with release 0.2.5. Please reopen if it's not the case.

**Closed by scambier** 2022-04-26 19:35 UTC
Labels: bug

**Comment by technicalpickles** [comment] 2022-05-01 17:54
Confirmed this is working now, thanks!
